// Generated by https://quicktype.io

export interface PageResponse {
  count: number;
  next: string;
  previous: null;
  results: Book[];
}

export interface Book {
  id: number;
  title: string;
  authors: Author[];
  translators: Author[];
  subjects: string[];
  bookshelves: string[];
  languages: Language[];
  copyright: boolean;
  media_type: MediaType;
  formats: { [key: string]: string };
  download_count: number;
}

export interface Author {
  name: string;
  birth_year: number | null;
  death_year: number | null;
}

export enum Language {
  En = "en",
}

export enum MediaType {
  Text = "Text",
}
